server {
    listen 80;
    access_log off;

    # Route WordPress Backend and Core Assets
    location ~* ^/(wp-admin|wp-login\.php|wp-content|wp-includes|wp-json) {
        proxy_pass http://wordpress:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Route everything else to the Vite app
    location / {
        proxy_pass http://next-js:3000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        
        proxy_intercept_errors on;
        error_page 404 = /index.html;
    }

    # Route Adminer Database Manager 
    location /db-admin {
        proxy_pass http://adminer:8080;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}