import type { Metadata } from "next";
import "./globals.css";
import wpGetLanguageAttributes from "@/lib/wordpress/functions/wpGetLanguageAttributes";
import wpGetBlogname from "@/lib/wordpress/functions/wpGetBlogname";
import wpGetFaviconURL from "@/lib/wordpress/functions/wpGetFaviconURL";

const [languageAttributes, blogname, iconURL] = await Promise.all([
  wpGetLanguageAttributes(),
  wpGetBlogname(),
  wpGetFaviconURL()
]);

export const metadata: Metadata = {
  title: blogname,
  // description: "Generated by create next app",
  icons: {
    icon: iconURL
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang={languageAttributes}
      >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
