import type { Metadata } from "next";
import "./globals.css";
import WPGetLanguageAttributes from "@/lib/wordpress/WPGetLanguageAttributes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const languageAttributes = await WPGetLanguageAttributes();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang={languageAttributes}
      >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
