import type { Metadata } from "next";
import "./globals.css";
import WPGetLanguageAttributes from "@/lib/wordpress/functions/WPGetLanguageAttributes";
import WPGetBlogname from "@/lib/wordpress/functions/WPGetBlogname";
import WPGetFaviconURL from "@/lib/wordpress/functions/WPGetFaviconURL";

const [languageAttributes, blogname, iconURL] = await Promise.all([
  WPGetLanguageAttributes(),
  WPGetBlogname(),
  WPGetFaviconURL()
]);

export const metadata: Metadata = {
  title: blogname,
  // description: "Generated by create next app",
  icons: {
    icon: iconURL
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang={languageAttributes}
      >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
